In [4]:
import sys
sys.path.append("..")

import pandas as pd
import numpy as np
from tabulate import tabulate

from Model.myutils import bin_numeric_df, run_tree_cv   
from Model.MyDecisionTree import MyDecisionTree         


In [6]:
# Load and bin dataset
df = pd.read_csv("../output_data/tmdb_clean_step1.csv")

numeric_cols = ['budget', 'popularity', 'vote_average',
                'vote_count', 'runtime', 'release_year']

df_binned = bin_numeric_df(df, numeric_cols, k=5, as_str=True)

X = df_binned.drop(columns=["main_genre"]).to_numpy().tolist()
y = df_binned["main_genre"].tolist()

# Run 10-fold CV
metrics_list = run_tree_cv(X, y, classifier_class=MyDecisionTree, k=10)

table_rows = []
for i, m in enumerate(metrics_list):
    acc, err, prec, rec, f1, cm = m
    table_rows.append([
        i,
        f"{acc:.3f}",
        f"{err:.3f}",
        f"{prec:.3f}",
        f"{rec:.3f}",
        f"{f1:.3f}",
        cm
    ])

print("# Decision Tree 10-fold CV")
print(tabulate(table_rows,
               headers=["Fold", "Acc", "Err", "Prec", "Rec", "F1", "Confusion"]))

avg_acc  = sum(m[0] for m in metrics_list) / len(metrics_list)
avg_err  = sum(m[1] for m in metrics_list) / len(metrics_list)
avg_prec = sum(m[2] for m in metrics_list) / len(metrics_list)
avg_rec  = sum(m[3] for m in metrics_list) / len(metrics_list)
avg_f1   = sum(m[4] for m in metrics_list) / len(metrics_list)

print("\n# Decision Tree")
print("Accuracy:", avg_acc)
print("Precision:", avg_prec)
print("Recall:", avg_rec)
print("F1:", avg_f1)


# Decision Tree 10-fold CV
  Fold    Acc    Err    Prec    Rec     F1  Confusion
------  -----  -----  ------  -----  -----  ---------------
     0  0.479  0.521   0.482  0.464  0.456  [[30 43 42]
                                             [20 67 57]
                                             [10 38 96]]
     1  0.509  0.491   0.535  0.501  0.495  [[39 44 40]
                                             [14 70 56]
                                             [ 8 36 96]]
     2  0.499  0.501   0.497  0.481  0.475  [[ 35  43  38]
                                             [ 21  59  55]
                                             [ 11  34 107]]
     3  0.449  0.551   0.458  0.445  0.441  [[41 41 40]
                                             [23 56 64]
                                             [16 38 84]]
     4  0.484  0.516   0.503  0.481  0.47   [[36 51 36]
                                             [16 68 64]
                                             [10 31 91]]
     