In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
from sklearn.model_selection import StratifiedKFold
import numpy as np
import pandas as pd

# --- Load CSV file ---
df = pd.read_csv('../output_data/tmdb_clean_step1.csv')

attribute = "main_genre"

X = df.drop(columns=[attribute])
y = df[attribute]

# --- Set up stratified K-fold ---
skf = StratifiedKFold(n_splits=10, shuffle=True)

accuracies = []
f1_scores = []
conf_matrices = []

for fold, (train_idx, test_idx) in enumerate(skf.split(X, y), start=1):
    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

    # --- Scale within each fold ---
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # --- Train KNN ---
    knn = KNeighborsClassifier(n_neighbors=20)
    knn.fit(X_train_scaled, y_train)

    # --- Predict ---
    y_pred = knn.predict(X_test_scaled)

    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred, average="macro")
    cm = confusion_matrix(y_test, y_pred)

    accuracies.append(acc)
    f1_scores.append(f1)
    conf_matrices.append(cm)

    print(f"\n--- Fold {fold} ---")
    print(f"Accuracy: {acc:.4f}")
    print(f"F1 (macro): {f1:.4f}")
    print("Confusion matrix:")
    print(cm)

# --- Summary ---
print("\n========================")
print("Final Cross-Validation Results")
print("========================")
print("Mean Accuracy:", np.mean(accuracies))
print("Mean F1 Score (macro):", np.mean(f1_scores))
print("Std Accuracy:", np.std(accuracies))
print("Std F1:", np.std(f1_scores))



--- Fold 1 ---
Accuracy: 0.4740
F1 (macro): 0.4339
Confusion matrix:
[[49 29 34  4]
 [27 83 30  7]
 [11 38 83  9]
 [17 36 11 13]]

--- Fold 2 ---
Accuracy: 0.4948
F1 (macro): 0.4596
Confusion matrix:
[[52 33 22  9]
 [19 77 38 13]
 [14 33 93  1]
 [12 27 22 16]]

--- Fold 3 ---
Accuracy: 0.4948
F1 (macro): 0.4677
Confusion matrix:
[[64 33 14  5]
 [26 71 41  9]
 [14 33 86  8]
 [11 30 19 17]]

--- Fold 4 ---
Accuracy: 0.4417
F1 (macro): 0.3997
Confusion matrix:
[[43 43 24  6]
 [24 73 36 13]
 [15 33 85  8]
 [10 30 26 11]]

--- Fold 5 ---
Accuracy: 0.4708
F1 (macro): 0.4464
Confusion matrix:
[[47 45 20  3]
 [27 74 34 11]
 [14 34 86  7]
 [12 29 18 19]]

--- Fold 6 ---
Accuracy: 0.5000
F1 (macro): 0.4510
Confusion matrix:
[[52 37 23  3]
 [15 95 30  6]
 [11 42 82  6]
 [18 32 17 11]]

--- Fold 7 ---
Accuracy: 0.4958
F1 (macro): 0.4613
Confusion matrix:
[[60 46  7  2]
 [24 80 35  7]
 [19 33 84  5]
 [20 32 12 14]]

--- Fold 8 ---
Accuracy: 0.4729
F1 (macro): 0.4499
Confusion matrix:
[[50 39 22  4