In [1]:
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
from sklearn.model_selection import StratifiedKFold
import numpy as np
import pandas as pd

# --- Load CSV file ---
df = pd.read_csv('../output_data/tmdb_clean_step1.csv')

attribute = "main_genre"

X = df.drop(columns=[attribute])
y = df[attribute]

# --- Set up stratified K-fold ---
skf = StratifiedKFold(n_splits=10, shuffle=True)

accuracies = []
f1_scores = []
conf_matrices = []

for fold, (train_idx, test_idx) in enumerate(skf.split(X, y), start=1):
    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

    # --- Scale within each fold ---
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # --- Train KNN ---
    knn = KNeighborsClassifier(n_neighbors=20)
    knn.fit(X_train_scaled, y_train)

    # --- Predict ---
    y_pred = knn.predict(X_test_scaled)

    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred, average="macro")
    cm = confusion_matrix(y_test, y_pred)

    accuracies.append(acc)
    f1_scores.append(f1)
    conf_matrices.append(cm)

    print(f"\n--- Fold {fold} ---")
    print(f"Accuracy: {acc:.4f}")
    print(f"F1 (macro): {f1:.4f}")
    print("Confusion matrix:")
    print(cm)

# --- Summary ---
print("\n========================")
print("Final Cross-Validation Results")
print("========================")
print("Mean Accuracy:", np.mean(accuracies))
print("Mean F1 Score (macro):", np.mean(f1_scores))
print("Std Accuracy:", np.std(accuracies))
print("Std F1:", np.std(f1_scores))



--- Fold 1 ---
Accuracy: 0.5658
F1 (macro): 0.5652
Confusion matrix:
[[58 38 20]
 [22 86 38]
 [14 43 84]]

--- Fold 2 ---
Accuracy: 0.5459
F1 (macro): 0.5388
Confusion matrix:
[[48 41 27]
 [14 93 39]
 [18 44 79]]

--- Fold 3 ---
Accuracy: 0.5310
F1 (macro): 0.5197
Confusion matrix:
[[42 53 21]
 [26 81 39]
 [16 34 91]]

--- Fold 4 ---
Accuracy: 0.5583
F1 (macro): 0.5554
Confusion matrix:
[[57 39 20]
 [34 78 34]
 [16 35 90]]

--- Fold 5 ---
Accuracy: 0.6005
F1 (macro): 0.5940
Confusion matrix:
[[ 55  33  27]
 [ 20 100  26]
 [ 13  42  87]]

--- Fold 6 ---
Accuracy: 0.5558
F1 (macro): 0.5537
Confusion matrix:
[[55 37 23]
 [29 83 35]
 [11 44 86]]

--- Fold 7 ---
Accuracy: 0.6129
F1 (macro): 0.6095
Confusion matrix:
[[59 40 16]
 [25 93 29]
 [11 35 95]]

--- Fold 8 ---
Accuracy: 0.5161
F1 (macro): 0.5142
Confusion matrix:
[[49 45 21]
 [23 77 47]
 [13 46 82]]

--- Fold 9 ---
Accuracy: 0.5831
F1 (macro): 0.5764
Confusion matrix:
[[51 47 17]
 [22 95 30]
 [13 39 89]]

--- Fold 10 ---
Accuracy: 0