In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

# --- Load CSV file ---
df = pd.read_csv('../output_data/tmdb_clean_step1.csv')

attribute = "main_genre"

X = df.drop(columns=[attribute])
y = df[attribute]

# --- Stratified K-fold ---
skf = StratifiedKFold(n_splits=10, shuffle=True)

accuracies = []
f1_scores = []
conf_matrices = []

for fold, (train_idx, test_idx) in enumerate(skf.split(X, y), start=1):
    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

    # --- Scale inside each fold ---
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled  = scaler.transform(X_test)

    # --- Gaussian Naive Bayes ---
    nb = GaussianNB()
    nb.fit(X_train_scaled, y_train)

    # --- Predict ---
    y_pred = nb.predict(X_test_scaled)

    # --- Metrics ---
    acc = accuracy_score(y_test, y_pred)
    f1  = f1_score(y_test, y_pred, average="macro")
    cm  = confusion_matrix(y_test, y_pred)

    accuracies.append(acc)
    f1_scores.append(f1)
    conf_matrices.append(cm)

    print(f"\n--- Fold {fold} ---")
    print(f"Accuracy: {acc:.4f}")
    print(f"F1 (macro): {f1:.4f}")
    print("Confusion matrix:")
    print(cm)

# --- Summary ---
print("\n===============================")
print("Final Cross-Validation Results")
print("===============================")
print(f"Mean Accuracy: {np.mean(accuracies):.4f}")
print(f"Mean F1 Score (macro): {np.mean(f1_scores):.4f}")
print(f"Std Accuracy: {np.std(accuracies):.4f}")
print(f"Std F1 Score: {np.std(f1_scores):.4f}")




--- Fold 1 ---
Accuracy: 0.4262
F1 (macro): 0.3491
Confusion matrix:
[[ 23  72  19   2]
 [ 12 122   9   4]
 [ 13  74  53   1]
 [  9  46  15   7]]

--- Fold 2 ---
Accuracy: 0.4096
F1 (macro): 0.3477
Confusion matrix:
[[ 34  56  21   5]
 [ 11 113  18   5]
 [ 10  84  43   4]
 [  8  50  12   7]]

--- Fold 3 ---
Accuracy: 0.4096
F1 (macro): 0.3406
Confusion matrix:
[[ 38  58  17   3]
 [ 14 106  21   6]
 [  8  82  50   1]
 [ 14  48  12   3]]

--- Fold 4 ---
Accuracy: 0.4271
F1 (macro): 0.3492
Confusion matrix:
[[ 35  63  16   2]
 [  8 113  23   2]
 [ 20  65  54   2]
 [  9  56   9   3]]

--- Fold 5 ---
Accuracy: 0.4333
F1 (macro): 0.3607
Confusion matrix:
[[ 30  64  18   3]
 [ 11 114  17   4]
 [  8  70  59   4]
 [ 10  53  10   5]]

--- Fold 6 ---
Accuracy: 0.4437
F1 (macro): 0.3738
Confusion matrix:
[[ 27  58  28   2]
 [ 10 120  13   3]
 [ 12  68  57   4]
 [ 10  40  19   9]]

--- Fold 7 ---
Accuracy: 0.4229
F1 (macro): 0.3710
Confusion matrix:
[[ 37  60  16   2]
 [ 14 116  11   5]
 [ 11  87 