In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

# --- Load CSV file ---
df = pd.read_csv('../output_data/tmdb_clean_step1.csv')

attribute = "main_genre"

X = df.drop(columns=[attribute])
y = df[attribute]

# --- Stratified K-fold ---
skf = StratifiedKFold(n_splits=10, shuffle=True)

accuracies = []
f1_scores = []
conf_matrices = []

for fold, (train_idx, test_idx) in enumerate(skf.split(X, y), start=1):
    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

    # --- Scale inside each fold ---
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled  = scaler.transform(X_test)

    # --- Gaussian Naive Bayes ---
    nb = GaussianNB()
    nb.fit(X_train_scaled, y_train)

    # --- Predict ---
    y_pred = nb.predict(X_test_scaled)

    # --- Metrics ---
    acc = accuracy_score(y_test, y_pred)
    f1  = f1_score(y_test, y_pred, average="macro")
    cm  = confusion_matrix(y_test, y_pred)

    accuracies.append(acc)
    f1_scores.append(f1)
    conf_matrices.append(cm)

    print(f"\n--- Fold {fold} ---")
    print(f"Accuracy: {acc:.4f}")
    print(f"F1 (macro): {f1:.4f}")
    print("Confusion matrix:")
    print(cm)

# --- Summary ---
print("\n===============================")
print("Final Cross-Validation Results")
print("===============================")
print(f"Mean Accuracy: {np.mean(accuracies):.4f}")
print(f"Mean F1 Score (macro): {np.mean(f1_scores):.4f}")
print(f"Std Accuracy: {np.std(accuracies):.4f}")
print(f"Std F1 Score: {np.std(f1_scores):.4f}")




--- Fold 1 ---
Accuracy: 0.5136
F1 (macro): 0.4964
Confusion matrix:
[[ 37  60  19]
 [  9 108  29]
 [  9  70  62]]

--- Fold 2 ---
Accuracy: 0.4913
F1 (macro): 0.4592
Confusion matrix:
[[ 35  56  25]
 [ 10 119  17]
 [ 13  84  44]]

--- Fold 3 ---
Accuracy: 0.5236
F1 (macro): 0.4874
Confusion matrix:
[[ 30  54  32]
 [ 13 120  13]
 [ 15  65  61]]

--- Fold 4 ---
Accuracy: 0.4764
F1 (macro): 0.4372
Confusion matrix:
[[ 28  66  22]
 [ 16 119  11]
 [  9  87  45]]

--- Fold 5 ---
Accuracy: 0.5087
F1 (macro): 0.4761
Confusion matrix:
[[ 36  61  18]
 [ 11 122  13]
 [ 18  77  47]]

--- Fold 6 ---
Accuracy: 0.5186
F1 (macro): 0.4879
Confusion matrix:
[[ 33  62  20]
 [ 11 120  16]
 [ 12  73  56]]

--- Fold 7 ---
Accuracy: 0.5211
F1 (macro): 0.4969
Confusion matrix:
[[ 32  64  19]
 [ 10 108  29]
 [ 12  59  70]]

--- Fold 8 ---
Accuracy: 0.4665
F1 (macro): 0.4350
Confusion matrix:
[[ 31  69  15]
 [ 11 114  22]
 [ 11  87  43]]

--- Fold 9 ---
Accuracy: 0.5186
F1 (macro): 0.4869
Confusion matrix:
[[